COMMON: &COMMON
  author: "Augument Null"
  source: "http://www.google.com/images/srpr/logo11w.png"
  width: 215
  height: 67
    
  development:
    hoge: "dev"
    <<: *COMMON
      
  test:
    hoge: "test"
    <<: *COMMON
      
  production:
    hoge: "pro"
    <<: *COMMON
